name = "mongo-realm-worker"
type = "javascript"
compatibility_date = "2024-02-03"

account_id = "fe4acbe203008f75f66fecb89df5e283"
workers_dev = true # or zone_id = "<ZONE ID>" if you have one

[build]
command = "npm run build"

[build.upload]
dir = "build"
main = "./index.mjs"
format = "modules"

[vars]
REALM_APPID = "cloudflare-rplef"
